name: slt-ce
channels:
  - conda-forge
dependencies:
  - python=3.5.3
  - scikit-learn
  - scikit-image
  - scipy
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - tensorflow
  - pip
  - pip:
    - treelib
    - pathos

  
